language: minimal

before_install:
#  - openssl aes-256-cbc -K $encrypted_290e5d6f0091_key -iv $encrypted_290e5d6f0091_iv
#    -in dashboard/som-rit-ourvoice-cred.json.enc -out dashboard/som-rit-ourvoice-cred.json -d


cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version


#deploy:
#  - provider: gae
#    keyfile: dashboard/som-rit-ourvoice-cred.json
#    project: som-rit-ourvoice
#    no_promote: true
#    config: dashboard/app.yaml
#    on:
#      branch: dev